#--------------------------------------
# Non-root user to create
#--------------------------------------
ARG USER_ID=1000
ARG USER_NAME=ubuntu

#--------------------------------------
# Image: containerbase/buildpack
#--------------------------------------
FROM containerbase/buildpack:1.18.0@sha256:16c164547e9461600a4ae179f9e973a3fc8148ab1093313b837b4e8fefc4be7a AS buildpack


#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:bionic@sha256:9bc830af2bef73276515a29aa896eedfa7bdf4bdbc5c1063b4c457a4bbb8cd79 as base

ARG USER_ID
ARG USER_NAME

LABEL maintainer="Rhys Arkins <rhys@arkins.net>" \
  org.opencontainers.image.source="https://github.com/renovatebot/docker-buildpack"

#  autoloading buildpack env
ENV BASH_ENV=/usr/local/etc/env PATH=/home/$USER_NAME/bin:$PATH
SHELL ["/bin/bash" , "-c"]

# This entry point ensures that dumb-init is run
ENTRYPOINT [ "docker-entrypoint.sh" ]
CMD [ "bash" ]

# Set up buildpack
COPY --from=buildpack /usr/local/bin/ /usr/local/bin/
COPY --from=buildpack /usr/local/buildpack/ /usr/local/buildpack/
RUN install-buildpack


# renovate: datasource=github-tags lookupName=git/git
RUN install-tool git v2.34.0


#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test

# renovate: datasource=docker lookupName=mcr.microsoft.com/dotnet/sdk versioning=docker
RUN install-tool dotnet 6.0.100

#disable renovate: datasource=github-releases lookupName=erlang/otp versioning=loose
RUN install-tool erlang 22.3.2
# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.12.3

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.17.3

# renovate: datasource=github-releases lookupName=helm/helm
RUN install-tool helm v3.7.1

# renovate: datasource=adoptium-java lookupName=java-jre
RUN install-tool java 11.0.13+8
# renovate: datasource=gradle-version lookupName=gradle versioning=gradle
RUN install-tool gradle 6.9.1

# renovate: datasource=github-releases lookupName=NixOS/nix
RUN install-tool nix 2.3.10

# renovate: datasource=node
RUN install-tool node v16.13.0
# renovate: datasource=npm
RUN install-tool pnpm 6.16.1
# renovate: datasource=npm
RUN install-tool yarn 1.22.17

# renovate: datasource=github-releases lookupName=containerbase/php-prebuild
RUN install-tool php 8.0.13
# renovate: datasource=github-releases depName=composer/composer
RUN install-tool composer 2.0.9

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool powershell v7.2.0

# renovate: datasource=github-releases lookupName=containerbase/python-prebuild
RUN install-tool python 3.9.9
# renovate: datasource=pypi
RUN install-pip pipenv 2021.11.23
# renovate: datasource=pypi
RUN install-pip hashin 0.15.0
# renovate: datasource=pypi
RUN install-tool poetry 1.1.11

# renovate: datasource=github-releases lookupName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.0.2
# renovate: datasource=rubygems versioning=ruby
RUN install-gem bundler 2.2.31
# renovate: datasource=rubygems versioning=ruby
RUN install-gem cocoapods 1.11.2

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.56.1

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.5.1
